import { $env, $flag } from "@oh-my-pi/pi-utils";

const SIXEL_END_SEQUENCE = "\x1b\\";
const SIXEL_END_BELL = "\x07";
const SIXEL_PLACEHOLDER_PREFIX = "__OMP_SIXEL_SEQUENCE_";

function sixelPayloadStart(text: string, start: number): number | null {
	if (!text.startsWith("\x1bP", start)) return null;
	let cursor = start + 2;
	while (cursor < text.length) {
		const code = text.charCodeAt(cursor);
		if ((code >= 48 && code <= 57) || code === 59) {
			cursor += 1;
			continue;
		}
		return text[cursor] === "q" ? cursor + 1 : null;
	}
	return null;
}

function nextSixelStart(text: string, from: number): number {
	for (let start = text.indexOf("\x1bP", from); start !== -1; start = text.indexOf("\x1bP", start + 2)) {
		if (sixelPayloadStart(text, start) !== null) return start;
	}
	return -1;
}

function sixelEnd(text: string, payloadStart: number): number {
	for (let cursor = payloadStart; cursor < text.length; cursor += 1) {
		if (text[cursor] === SIXEL_END_BELL) return cursor + SIXEL_END_BELL.length;
		if (text.startsWith(SIXEL_END_SEQUENCE, cursor)) return cursor + SIXEL_END_SEQUENCE.length;
	}
	return -1;
}

/**
 * Returns whether SIXEL passthrough is explicitly enabled.
 *
 * Both gates must be enabled to preserve SIXEL control sequences:
 * - PI_FORCE_IMAGE_PROTOCOL=sixel
 * - PI_ALLOW_SIXEL_PASSTHROUGH=1
 */
export function isSixelPassthroughEnabled(): boolean {
	const forcedProtocol = $env.PI_FORCE_IMAGE_PROTOCOL?.trim().toLowerCase();
	return forcedProtocol === "sixel" && $flag("PI_ALLOW_SIXEL_PASSTHROUGH");
}
/** Returns true when the text contains a SIXEL start sequence. */
export function containsSixelSequence(text: string): boolean {
	return nextSixelStart(text, 0) !== -1;
}

/**
 * Returns a boolean mask indicating which lines belong to a SIXEL sequence block.
 * Supports multi-line SIXEL payloads generated by libsixel.
 */
export function getSixelLineMask(lines: readonly string[]): boolean[] {
	let inSequence = false;
	return lines.map(line => {
		const hasStart = containsSixelSequence(line);
		if (hasStart) {
			inSequence = true;
		}
		const isSixelLine = inSequence;
		if (inSequence && (line.includes(SIXEL_END_SEQUENCE) || line.includes(SIXEL_END_BELL))) {
			inSequence = false;
		}
		return isSixelLine;
	});
}

/** Returns true when the line contains a SIXEL start sequence. */
export function isSixelLine(line: string): boolean {
	return containsSixelSequence(line);
}

/**
 * Sanitizes text while preserving embedded SIXEL sequences when passthrough is enabled.
 */
export function sanitizeWithOptionalSixelPassthrough(text: string, sanitize: (text: string) => string): string {
	if (!isSixelPassthroughEnabled() || !containsSixelSequence(text)) {
		return sanitize(text);
	}

	const preservedSequences: string[] = [];
	let tokenized = "";
	let cursor = 0;
	let scan = 0;
	for (;;) {
		const start = nextSixelStart(text, scan);
		if (start === -1) break;
		const payloadStart = sixelPayloadStart(text, start)!;
		const end = sixelEnd(text, payloadStart);
		if (end === -1) {
			break;
		}
		tokenized += text.slice(cursor, start);
		tokenized += `${SIXEL_PLACEHOLDER_PREFIX}${preservedSequences.length}__`;
		preservedSequences.push(text.slice(start, end));
		cursor = end;
		scan = end;
	}
	tokenized += text.slice(cursor);

	const sanitized = sanitize(tokenized);
	let restored = "";
	cursor = 0;
	for (;;) {
		const start = sanitized.indexOf(SIXEL_PLACEHOLDER_PREFIX, cursor);
		if (start === -1) return restored + sanitized.slice(cursor);
		let end = start + SIXEL_PLACEHOLDER_PREFIX.length;
		while (end < sanitized.length && sanitized.charCodeAt(end) >= 48 && sanitized.charCodeAt(end) <= 57) end += 1;
		if (end === start + SIXEL_PLACEHOLDER_PREFIX.length || sanitized.slice(end, end + 2) !== "__") {
			restored += sanitized.slice(cursor, end);
			cursor = end;
			continue;
		}
		const index = Number.parseInt(sanitized.slice(start + SIXEL_PLACEHOLDER_PREFIX.length, end), 10);
		restored += sanitized.slice(cursor, start) + (preservedSequences[index] ?? "");
		cursor = end + 2;
	}
}
